Traceback (most recent call last):
  File "/home/adimech/.local/lib/python3.6/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/adimech/.local/lib/python3.6/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/adimech/.local/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/adimech/.local/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/adimech/.local/lib/python3.6/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/adimech/.local/lib/python3.6/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/adimech/.local/lib/python3.6/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import qgrid

qgrid.set_grid_option('maxVisibleRows', 10)
qgrid.show_grid(df)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-5-0f47ce3b107e>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0mqgrid[0m[0;34m.[0m[0mset_grid_option[0m[0;34m([0m[0;34m'maxVisibleRows'[0m[0;34m,[0m [0;36m10[0m[0;34m)[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0mqgrid[0m[0;34m.[0m[0mshow_grid[0m[0;34m([0m[0mdf[0m[0;34m)[0m[0;34m[0m[0m
[0m
[0;32m~/.local/lib/python3.6/site-packages/qgrid/grid.py[0m in [0;36mshow_grid[0;34m(data_frame, show_toolbar, remote_js, precision, grid_options, export_mode)[0m
[1;32m    216[0m     grid = QGridWidget(df=data_frame, precision=precision,
[1;32m    217[0m                        [0mgrid_options[0m[0;34m=[0m[0mgrid_options[0m[0;34m,[0m[0;34m[0m[0m
[0;32m--> 218[0;31m                        remote_js=remote_js)
[0m[1;32m    219[0m [0;34m[0m[0m
[1;32m    220[0m     [0;32mif[0m [0mshow_toolbar[0m[0;34m:[0m[0;34m[0m[0m

[0;32m~/.local/lib/python3.6/site-packages/qgrid/grid.py[0m in [0;36m__init__[0;34m(self, *args, **kwargs)[0m
[1;32m    262[0m         [0mself[0m[0;34m.[0m[0m_selected_rows[0m [0;34m=[0m [0;34m[[0m[0;34m][0m[0;34m[0m[0m
[1;32m    263[0m         [0;32mif[0m [0mself[0m[0;34m.[0m[0mdf[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0m
[0;32m--> 264[0;31m             [0mself[0m[0;34m.[0m[0m_update_table[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0m
[0m[1;32m    265[0m [0;34m[0m[0m
[1;32m    266[0m     [0;32mdef[0m [0m_grid_options_default[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0m

[0;32m~/.local/lib/python3.6/site-packages/qgrid/grid.py[0m in [0;36m_update_table[0;34m(self)[0m
[1;32m    286[0m             [0mdf[0m[0;34m.[0m[0mindex[0m[0;34m.[0m[0mname[0m [0;34m=[0m [0;34m'Index'[0m[0;34m[0m[0m
[1;32m    287[0m [0;34m[0m[0m
[0;32m--> 288[0;31m         [0;32mif[0m [0mtype[0m[0;34m([0m[0mdf[0m[0;34m.[0m[0mindex[0m[0;34m)[0m [0;34m==[0m [0mpd[0m[0;34m.[0m[0mcore[0m[0;34m.[0m[0mindex[0m[0;34m.[0m[0mMultiIndex[0m[0;34m:[0m[0;34m[0m[0m
[0m[1;32m    289[0m             [0mdf[0m[0;34m.[0m[0mreset_index[0m[0;34m([0m[0minplace[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0m
[1;32m    290[0m             [0mself[0m[0;34m.[0m[0m_multi_index[0m [0;34m=[0m [0;32mTrue[0m[0;34m[0m[0m

[0;31mAttributeError[0m: module 'pandas.core' has no attribute 'index'
AttributeError: module 'pandas.core' has no attribute 'index'

